name: quickflick

services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/db/mongo-keyfile"]
    volumes:
      - mongo_data:/data/db
    env_file:
      - stack.env

  backend:
    image: praveenmalethia/quick-flick-backend:staging-dbbf625
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - mongodb
    volumes:
      - backend_uploads:/usr/src/app/uploads
      - backend_logs:/usr/src/app/logs

  admin:
    image: praveenmalethia/quick-flick-admin:staging-2c2cd29
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - backend

  frontend:
    image: praveenmalethia/quick-flick-frontend:staging-4638f9c
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    env_file:
      - stack.env

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  backend_uploads:
  backend_logs:
  redis_data:

networks:
  default:
    ipam:
      config:
        - subnet: 10.20.0.0/16