name: quickflick

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    env_file:
      - stack.env

  backend:
    image: praveenmalethia/quick-flick-backend:main-placeholder
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - mongodb
    volumes:
      - backend_uploads:/usr/src/app/uploads
      - backend_logs:/usr/src/app/logs

  admin:
    image: praveenmalethia/quick-flick-admin:main-350573e
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - backend

  frontend:
    image: praveenmalethia/quick-flick-frontend:main-d7ba657
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    env_file:
      - stack.env

volumes:
  mongo_data:
  backend_uploads:
  backend_logs:

networks:
  default:
    ipam:
      config:
        - subnet: 10.21.0.0/16