name: quickflick

services:
  mongodb:
    build: ./mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    env_file:
      - stack.env
    healthcheck:
      test: mongosh --eval "rs.status().ok" --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    image: praveenmalethia/quick-flick-backend:main-8af2368
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - backend_uploads:/usr/src/app/uploads
      - backend_logs:/usr/src/app/logs

  admin:
    image: praveenmalethia/quick-flick-admin:main-350573e
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - backend

  frontend:
    image: praveenmalethia/quick-flick-frontend:main-d7ba657
    restart: unless-stopped
    env_file:
      - stack.env
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    env_file:
      - stack.env

volumes:
  mongo_data:
  backend_uploads:
  backend_logs:

networks:
  default:
    ipam:
      config:
        - subnet: 10.21.0.0/16